### PR TITLE
Add transaction type column

### PR DESCRIPTION
**Pull request by titusz**

### CODE REVIEW

**Comment by titusz** [comment]
For users installing this version on top of an existing installation we would need some mechanism to detect that there has been a db schema update. Killing the existing db and rebuilding should do the trick.

**Comment by titusz** [comment]
The transaction type column takes to much space in the table with redundant information:

image

We should use either a short small constant width text label or a icon to indicate transaction type and maybe put it in the first column?

**Comment by Swarlston** [comment]
Icons sound good to me, along with some hover text that should be better.

**Comment by titusz** [comment]
This is the current state:

image

Up for discussion :)

**Pull request merged**
